"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tournament = "query TournamentQuery($slug: String) {\n    tournament(slug: $slug){\n        id\n        name\n        slug\n        city\n        postalCode\n        addrState\n        countryCode\n        region\n        venueAddress\n        venueName\n        gettingThere\n        lat\n        lng\n        timezone\n        startAt\n        endAt\n        contactInfo\n        contactEmail\n        contactTwitter\n        contactPhone\n        ownerId\n    }\n}";
exports.tournamentOrganizer = "query tournamentOrganizer($slug: String){\n    tournament(slug: $slug){\n        ownerId\n        contactEmail\n        contactTwitter\n        contactPhone\n        contactInfo\n    }   \n}";
exports.tournamentVenue = "query tournamentVenue($slug: String) {\n\ttournament(slug: $slug){\n\t\tvenueName\n\t\tvenueAddress\n\t\tcity\n\t\taddrState\n\t\tcountryCode\n\t}\t\n}";
exports.tournamentPlayers = "query TournamentParticipantQuery($slug: String) {\n    tournament(slug: $slug){\n        id\n        name\n        slug\n        participants(query: {\n            page: 0,\n            perPage: 10000,\n            sortBy: \"asc\",\n        },\n        isAdmin: false){\n            nodes{\n                id\n                playerId\n                gamerTag\n                prefix\n            }\n        }\n    }  \n}";
exports.tournamentPhases = "query TournamentPhases($slug: String){\n    tournament(slug: $slug){\n        id\n        name\n        slug\n        events{\n            id\n            name\n            slug\n            phases{\n                id\n                name\n                numSeeds\n                groupCount\n            }\n        }\n    }   \n}";
exports.tournamentPhaseGroups = "query TournamentPhaseGroups($slug: String){\n    tournament(slug: $slug){\n        id\n        name\n        slug\n        events{\n            id\n            name\n            slug\n            phaseGroups{\n                id\n                phaseId\n                waveId\n                state\n                firstRoundTime\n                displayIdentifier\n            }\n        }\n    }   \n}";
/** WARNING THIS DOES NOT WORK CURRENTLY DUE TO RECURSIVE LIMITATIONS, Use tournamentPhaseGroupIds instead **/
exports.tournamentSets = "query TournamentSets($slug: String){ \n    tournament(slug: $slug){\n        events{\n            phaseGroups{\n                sets{\n                    id\n                    round\n                    fullRoundText\n                    startedAt\n                    completedAt\n                    winnerId\n                    totalGames\n                    state\n                    slots{\n                        id\n                        entrant {\n                            id\n                            name\n                            participants {\n                                id\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }   \n}";
exports.tournamentPhaseGroupIds = "query PhaseGroupIdQuery($slug: String) {\n    tournament(slug: $slug){\n        events{\n            id\n            phaseGroups{\n                id\n            }\n        }\n    }\n}";
